"""empty message

Revision ID: 5802b21798ca
Revises: 7709bf7f4dc3
Create Date: 2024-03-04 22:13:12.122313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5802b21798ca'
down_revision = '7709bf7f4dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_burger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('burger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['burger_id'], ['burger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('burger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['burger_id'], ['burger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart')
    op.drop_table('favorite_burger')
    # ### end Alembic commands ###
