"""empty message

Revision ID: 7709bf7f4dc3
Revises: ea909c807262
Create Date: 2024-02-28 20:05:25.742196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7709bf7f4dc3'
down_revision = 'ea909c807262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('z_index',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('z_index',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
