"""empty message

Revision ID: 95bf081de6c4
Revises: bace877dfd22
Create Date: 2024-02-24 00:43:33.234072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bf081de6c4'
down_revision = 'bace877dfd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.drop_column('burger_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burger_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
