"""empty message

Revision ID: bace877dfd22
Revises: ec6d0c854639
Create Date: 2024-02-24 00:38:31.014483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bace877dfd22'
down_revision = 'ec6d0c854639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('burger_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burger_to_ingredient',
    sa.Column('burger_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['burger_id'], ['burger.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], )
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('image')

    op.drop_table('burger_to_ingredient')
    op.drop_table('burger')
    # ### end Alembic commands ###
